version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx_webserver
    ports:
      - "8834:80"
    volumes:
      - ./app_data:/var/www/html
      - ./nginx_conf/default.conf/:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql_server
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: kyawgyi
      MYSQL_DATABASE: kyawgyi
      MYSQL_USER: kyawgyi
      MYSQL_PASSWORD: kyawgyi
      
  php:
    build: .
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./app_data:/var/www/html

